# Generated by Django 2.1 on 2018-08-26 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonbatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='students',
            table='students',
        ),
    ]
